# Generated by Django 4.2.21 on 2025-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_admin_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='telegram_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
