# Generated by Django 4.2.21 on 2025-05-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_admin_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
