# Generated by Django 4.2.21 on 2025-06-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_admin_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ofd_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.organization'),
        ),
    ]
