# Generated by Django 4.2.21 on 2025-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
