# Generated by Django 4.2.21 on 2025-06-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_receipt_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='type',
            field=models.CharField(blank=True, choices=[('prescription', 'Рецепт'), ('check', 'Чек')], max_length=20, null=True),
        ),
    ]
