# Generated by Django 4.2.21 on 2025-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_receipt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название розыгрыша')),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма приза')),
                ('date_from', models.DateField(verbose_name='Начало периода')),
                ('date_to', models.DateField(verbose_name='Конец периода')),
                ('winner_criteria', models.CharField(blank=True, choices=[('count', 'По количеству рецептов/чеков'), ('total_amount', 'По сумме выписанного')], max_length=20, null=True, verbose_name='Критерий победителя')),
                ('user_type', models.CharField(choices=[('all', 'Все'), ('doctor', 'Врач'), ('pharmacist', 'Фармацевт')], default='all', max_length=20, verbose_name='Тип участников розыгрыша')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
