# Generated by Django 4.2.21 on 2025-06-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_giveaway'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Админы'},
        ),
        migrations.AlterModelOptions(
            name='giveaway',
            options={'verbose_name': 'Розыгрыш', 'verbose_name_plural': 'Розыгрыши'},
        ),
        migrations.AlterModelOptions(
            name='invitelink',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Ораганизации'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Рецепт/Чек', 'verbose_name_plural': 'Рецепты/Чеки'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='giveaway',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='winner_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество победителей'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='winner_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные победителей'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('uz', 'Uzbek')], max_length=10, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='user_type',
            field=models.CharField(choices=[('all', 'Все'), ('doctor', 'Врачи'), ('pharmacist', 'Фармацевты')], default='all', max_length=20, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='winner_criteria',
            field=models.CharField(blank=True, choices=[('count', 'По количеству'), ('total_amount', 'По сумме')], max_length=20, null=True, verbose_name='Критерий выбора победителя'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to='app.admin', verbose_name='Кем приглашен'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='token',
            field=models.UUIDField(unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Использовано'),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='Кем использовано'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('pharmacy', 'Аптека'), ('medical_institution', 'Медицинское учреждение')], max_length=50, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.JSONField(blank=True, null=True, verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ofd_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Soliq'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.CharField(max_length=255, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(blank=True, choices=[('prescription', 'Рецепт'), ('check', 'Чек')], max_length=20, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin', verbose_name='Кем обновлено'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название Ру'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название Уз'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('uz', 'Uzbek')], max_length=10, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Врач'), ('pharmacist', 'Фармацевт')], max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
