# Generated by Django 4.2.21 on 2025-06-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_admin_options_alter_giveaway_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatisticsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика по пользователям',
                'verbose_name_plural': 'Статистика по пользователям',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='date_from',
            field=models.DateField(verbose_name='Начало розыгрыша'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='date_to',
            field=models.DateField(verbose_name='Конец розыгрыша'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='winner_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Победители'),
        ),
    ]
