# Generated by Django 4.2.21 on 2025-06-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userstatisticsproxy_alter_giveaway_date_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatisticsproxy',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
