# Generated by Django 4.2.21 on 2025-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userstatisticsproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма'),
        ),
    ]
